// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OrderShip order ship
// swagger:model orderShip
type OrderShip struct {

	// Tracking number of package
	TrackingNumber string `json:"trackingNumber,omitempty"`

	// Override predicted weight of package
	WeightOverride float32 `json:"weightOverride,omitempty"`
}

// Validate validates this order ship
func (m *OrderShip) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderShip) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderShip) UnmarshalBinary(b []byte) error {
	var res OrderShip
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
