// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Pagination pagination
// swagger:model pagination
type Pagination struct {

	// Count of records returned in response, this will be equal to or less then the limit paramater
	Count int64 `json:"count,omitempty"`

	// Current page of the response, this will match the page paramater
	CurrentPage int64 `json:"currentPage,omitempty"`

	// Total number of records available to request
	Total int64 `json:"total,omitempty"`

	// Total number of pages available to request
	TotalPages int64 `json:"totalPages,omitempty"`
}

// Validate validates this pagination
func (m *Pagination) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Pagination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pagination) UnmarshalBinary(b []byte) error {
	var res Pagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
