// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StatusTypeSimple status type simple
// swagger:model statusTypeSimple
type StatusTypeSimple struct {

	// Human-readable description
	// Required: true
	Reason *string `json:"reason"`

	// status
	// Required: true
	Status *StatusTypeSimpleStatus `json:"status"`
}

// Validate validates this status type simple
func (m *StatusTypeSimple) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReason(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StatusTypeSimple) validateReason(formats strfmt.Registry) error {

	if err := validate.Required("reason", "body", m.Reason); err != nil {
		return err
	}

	return nil
}

func (m *StatusTypeSimple) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StatusTypeSimple) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StatusTypeSimple) UnmarshalBinary(b []byte) error {
	var res StatusTypeSimple
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// StatusTypeSimpleStatus status type simple status
// swagger:model StatusTypeSimpleStatus
type StatusTypeSimpleStatus struct {

	// code
	// Required: true
	// Pattern: ^\d{6}$
	Code *string `json:"code"`
}

// Validate validates this status type simple status
func (m *StatusTypeSimpleStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StatusTypeSimpleStatus) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("status"+"."+"code", "body", m.Code); err != nil {
		return err
	}

	if err := validate.Pattern("status"+"."+"code", "body", string(*m.Code), `^\d{6}$`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StatusTypeSimpleStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StatusTypeSimpleStatus) UnmarshalBinary(b []byte) error {
	var res StatusTypeSimpleStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
