// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TrackingNumber tracking number
// swagger:model trackingNumber
type TrackingNumber struct {

	// The computer readable alternative to the human readable
	BarcodeScanValue string `json:"barcodeScanValue,omitempty"`

	// carrier
	Carrier string `json:"carrier,omitempty"`

	// The human readable tracking number recipients (consignee) expect
	Value string `json:"value,omitempty"`
}

// Validate validates this tracking number
func (m *TrackingNumber) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TrackingNumber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TrackingNumber) UnmarshalBinary(b []byte) error {
	var res TrackingNumber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
